// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGJNbPhqYAxBt9UehihkrwMzv0auhLtQ',
    appId: '1:165574279956:android:89503ba3228278303ab801',
    messagingSenderId: '165574279956',
    projectId: 'hela-trip',
    storageBucket: 'hela-trip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRw2yCI03ZLjRiYxUWLQ3IEoYRVRXEohc',
    appId: '1:165574279956:ios:2a078902e616b7323ab801',
    messagingSenderId: '165574279956',
    projectId: 'hela-trip',
    storageBucket: 'hela-trip.firebasestorage.app',
    iosBundleId: 'com.example.helaTrip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyn0W8GRF6SZGOPqsDDlLbIdHPSJOKr70',
    appId: '1:165574279956:web:220a4bb55a5bcdfd3ab801',
    messagingSenderId: '165574279956',
    projectId: 'hela-trip',
    authDomain: 'hela-trip.firebaseapp.com',
    storageBucket: 'hela-trip.firebasestorage.app',
    measurementId: 'G-XQQVFT7RH5',
  );

}